version: '3.4'

services:
  verticalslicearchitecture.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5004
      - ASPNETCORE_HTTPS_PORTS=5005
    ports:
      - "5004"
      - "5005"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro